Update tor.yml

diff --git a/.github/workflows/tor.yml b/.github/workflows/tor.yml
--- a/.github/workflows/tor.yml
+++ b/.github/workflows/tor.yml
@@ -20,7 +20,7 @@ jobs:
         git clone --depth 1 https://github.com/anuragmuxui/anuragmuxui.github.io.git site-content
         ls site-content
 
-    - name: Deploy to Tor
+        - name: Deploy to Tor
       run: |
         # Install Docker Engine
         sudo apt-get update
@@ -29,15 +29,6 @@ jobs:
           curl \
           gnupg \
           lsb-release
-
-        # Set up the Docker repository
-        sudo mkdir -p /etc/apt/keyrings
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
-        echo \
-          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
-          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-        sudo apt-get update
-        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
 
         # Create necessary directories
         mkdir -p hidden_service
@@ -63,16 +54,17 @@ jobs:
 
         # Wait for the .onion address to be generated
         echo "Waiting for the .onion address to be generated..."
-        sleep 30
+        for i in {1..12}; do
+          if [ -f hidden_service/hostname ]; then
+            echo "Tor hidden service address:"
+            cat hidden_service/hostname
+            exit 0
+          fi
+          sleep 10
+        done
 
-        # Display the generated .onion address
-        if [ -f hidden_service/hostname ]; then
-          echo "Tor hidden service address:"
-          cat hidden_service/hostname
-        else
-          echo "Error: Hidden service address not found."
-          exit 1
-        fi
+        echo "Error: Hidden service address not found."
+        exit 1
 
 
     - name: Save .onion Address
